### ISSUE TITLE
[detect-1]killing on exit

### ISSUE THREAD

**Issue by PauloASMendes** [mats-robotics/yolov5_ros#1]
RLException: Unable to launch [detect-1]. 
If it is a script, you may be missing a '#!' declaration at the top.
The traceback for the exception was written to the log file

When I try to run roslaunch yolov5_ros yolov5.launch it returns this error message. What should I do?

**Comment by PauloASMendes** [comment]
More precisely.

... logging to /home/user/.ros/log/313bccb0-b9be-11ec-b5ea-08d40c64d5d9/roslaunch-pauloasmendes-Lenovo-ideapad-300-15ISK-15273.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://user:40289/

SUMMARY
========

PARAMETERS
 * /detect/agnostic_nms: True
 * /detect/confidence_threshold: 0.5
 * /detect/data: /home/pauloasmend...
 * /detect/device: 0
 * /detect/dnn: True
 * /detect/half: False
 * /detect/inference_size_h: 640
 * /detect/inference_size_w: 640
 * /detect/input_image_topic: /camera/color/ima...
 * /detect/iou_threshold: 0.45
 * /detect/line_thickness: 3
 * /detect/maximum_detections: 1000
 * /detect/output_image_topic: /yolov5/image_out
 * /detect/output_topic: /yolov5/detections
 * /detect/publish_image: True
 * /detect/view_image: True
 * /detect/weights: yolov5m.pt
 * /rosdistro: melodic
 * /rosversion: 1.14.13

NODES
  /
    detect (yolov5_ros/detect.py)

ROS_MASTER_URI=http://localhost:11311

RLException: Unable to launch [detect-1]. 
If it is a script, you may be missing a '#!' declaration at the top.
The traceback for the exception was written to the log file
[detect-1] killing on exit

**Comment by nhat-m-le** [comment]
Hi Paulo,

I will look into the issue but for now I am not sure where the error comes from. Is YOLOv5 working on your machine? Could you try run it independently without the ROS wrapper?

**Comment by PauloASMendes** [comment]
Yes. Yolov5 is running smoothly. I tried it a lot of times.

**Comment by PauloASMendes** [comment]
I am using Ubuntu 18.04 and ROS melodic.

**Comment by abhishekt711** [comment]
> I am using Ubuntu 18.04 and ROS melodic.

I am also facing the same issue. IS your error resolved then please help me?

**Comment by HooradAboo** [comment]
Hi Paulo,
Did you find any solution? I have the same problem, too.

**Comment by abhishekt711** [comment]
Yes in the first line of script change to this #! /usr/bin/env python3

**Comment by HooradAboo** [comment]
Thanks for your response.
I did this, too. It does not work for me.

**Comment by nhat-m-le** [comment]
@HooradAboo @PauloMendes33 hi sorry I haven't had time to work with Ubuntu 18.04 and ROS Melodic. Could you try to follow the instruction here http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment for Python 3 users in ROS Melodic and earlier? I just also added to the repo instruction the step to make the Python script executable in case you have not done it yet.

**Comment by HooradAboo** [comment]
Thank you so much.
I compile it with "catkin_make" instead of "catkin build" and it works for me.
