### ISSUE TITLE
AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from ...

### ISSUE THREAD

**Issue by TDVL** [mats-robotics/yolov5_ros#12]
Hello,
I have this error when I launch the yolov5 package: AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from '/home/osboxes/catkin_ws/src/yolov5_ros/src/yolov5/models/yolo.py'>
![Screenshot from 2022-09-19 16-06-13](https://user-images.githubusercontent.com/47524135/191038157-f47792ed-427d-4a95-b5f4-34e6bfd582e4.png)
What is the reason of this error?
Thank you

**Comment by tehantehan** [comment]
i have the same issue :/

**Comment by mingleeeeee** [comment]
replace with the file below:
https://github.com/ultralytics/yolov5/blob/master/models/yolo.py

**Comment by nhat-m-le** [comment]
Issue is not present with the current commit of the yolov5 submodule
