### ISSUE TITLE
error unsupported format when loading .engine model

### ISSUE THREAD

**Issue by sjahanshahi** [mats-robotics/yolov5_ros#13]
Hi 
thanks for this repo, I am able to run .pt models without an error, however, when I try to run the .engine model, it throws an error.

could you advise how to load the custom trt engine model?
thanks

**Comment by nhat-m-le** [comment]
Hi, sorry I won't have time to investigate this. Please raise this issue to the [official YOLOv5 repository](https://github.com/ultralytics/yolov5)
