### ISSUE TITLE
Location of detection_msg.msg unknown

### ISSUE THREAD

**Issue by orlandocloss** [mats-robotics/yolov5_ros#15]
from detection_msgs.msg import BoundingBox, BoundingBoxes
ImportError: cannot import name 'BoundingBox' from 'detection_msgs.msg' (unknown location)
[detect-2] process has died [pid 39904, exit code 1, cmd /mnt/sda1/mythronics/catkin_ws/devel/lib/yolov5_ros/detect.py __name:=detect __log:=/home/orlando/.ros/log/b82baad2-9a47-11ed-946e-f16c2c6778ab/detect-2.log].
log file: /home/orlando/.ros/log/b82baad2-9a47-11ed-946e-f16c2c6778ab/detect-2*.log

**Comment by nhat-m-le** [comment]
Please follow the instruction for cloning and building the package.

Additionally, the direct link for the message package is here: https://github.com/mats-robotics/detection_msgs
