### ISSUE TITLE
Error running  roslaunch yolov5_ros yolov5.launch

### ISSUE THREAD

**Issue by programmeriop** [mats-robotics/yolov5_ros#16]
I tried to run :

'''$ roslaunch yolov5_ros yolov5.launch'''

and received the following error: 

''''... logging to /home/user/catkin_ws/src/ros_logs/230c2286-b9f7-11ed-8f8d-48b02da5202c/roslaunch-ubuntu-226443.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:34229/

SUMMARY
========

PARAMETERS
 * /detect/agnostic_nms: True
 * /detect/confidence_threshold: 0.75
 * /detect/data: /home/convergetec...
 * /detect/device: 0
 * /detect/dnn: True
 * /detect/half: False
 * /detect/inference_size_h: 640
 * /detect/inference_size_w: 640
 * /detect/input_image_topic: /ouster/reflec_image
 * /detect/iou_threshold: 0.45
 * /detect/line_thickness: 3
 * /detect/maximum_detections: 1000
 * /detect/output_image_topic: /yolov5/image_out
 * /detect/output_topic: /yolov5/detections
 * /detect/publish_image: False
 * /detect/view_image: True
 * /detect/weights: [best.pt](http://best.pt/)
 * /rosdistro: noetic
 * /rosversion: 1.15.15

NODES
  /
    detect (yolov5_ros/detect.py)

ROS_MASTER_URI=http://localhost:11311/

process[detect-1]: started with pid [226469]
/home/user/.local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/home/convergetech/catkin_wst/devel/lib/yolov5_ros/detect.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/convergetech/catkin_wst/src/yolov5_ros/src/detect.py", line 198, in <module>
    detector = Yolov5Detector()
  File "/home/user/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/catkin_wst/src/yolov5_ros/src/detect.py", line 51, in __init__
    self.device = select_device(str(rospy.get_param("~device","")))
  File "/home/convergetech/catkin_wst/src/yolov5_ros/src/yolov5/utils/torch_utils.py", line 117, in select_device
    assert torch.cuda.is_available() and torch.cuda.device_count() >= len(device.replace(',', '')), \
AssertionError: Invalid CUDA '--device 0' requested, use '--device cpu' or pass valid CUDA device(s)
[detect-1] process has died [pid 226469, exit code 1, cmd /home/convergetech/catkin_wst/devel/lib/yolov5_ros/detect.py __name:=detect __log:=/home/user/catkin_ws/src/ros_logs/230c2286-b9f7-11ed-8f8d-48b02da5202c/detect-1.log].
log file: /home/user/catkin_ws/src/230c2286-b9f7-11ed-8f8d-48b02da5202c/detect-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete```

Could you please tell me how to solve this?

**Comment by mattm8600** [comment]
Hi, I ran into a similar issue. This error probably means that your NVIDIA drivers are broken. I would run nvidia-smi and see what that gives you. I fixed this error by blacklisting the default graphics driver for Ubuntu and reinstalling the NVIDIA drivers.
