### ISSUE TITLE
pip install -r requirements.txt 

### ISSUE THREAD

**Issue by yisuoyanyu1** [mats-robotics/yolov5_ros#21]
ERROR: Could not find a version that satisfies the requirement matplotlib>=3.2.2 (from -r requirements.txt (line 5)) (from versions: none)
ERROR: No matching distribution found for matplotlib>=3.2.2 (from -r requirements.txt (line 5))

**Comment by nhat-m-le** [comment]
Sorry I will not have the resource to reproduce the error.
