### ISSUE TITLE
Real time object Segmentation on a ROS image topic

### ISSUE THREAD

**Issue by engrkhan** [mats-robotics/yolov5_ros#22]
Hello, 

Currently, the yolov5_ros packages uses YOLOv5 for real time object detection and publishes result on a ROS topic. It uses [this](https://github.com/ultralytics/yolov5/tree/23701eac7a7b160e478ba4bbef966d0af9348251) branch of the yolov5 github repo to do object detection.

My question is, if I use the [master](https://github.com/ultralytics/yolov5/tree/master) branch which allows for image segmentation, what changes need to be made to the [detect script ](https://github.com/mats-robotics/yolov5_ros/blob/main/src/detect.py)to publish result of segmentation on a ros topic? What could be the message type in this case?

In the attachment, I have shown result of strawberry segmentation done with YOLO v5. In the next step, I want to use this result to extract point cloud of one of the segmented strawberries for robot picking.

Thank you.

![yolov5_segmentation](https://github.com/mats-robotics/yolov5_ros/assets/3997674/bdaf0c2e-ea34-49a6-b2a4-326c7bc3a176)

**Comment by nhat-m-le** [comment]
we currently don't have any plan to keep it up-to-date with the latest changes/features in YOLOv5 official repository
