### ISSUE TITLE
Unable to view the output topic in RVIZ of ROS.

### ISSUE THREAD

**Issue by abhishekt711** [mats-robotics/yolov5_ros#3]

**Comment by nhat-m-le** [comment]
@abhishekt711 Hi, could you give some more details? I haven't tried to view it with Rviz yet and currently don't have a working camera.

**Comment by abhishekt711** [comment]
Yes the code is working properly and able to visualize the detection. But in RVIZ the output topic comes under invisible topics. So can we visualize the output topic in ROS ??

**Comment by nhat-m-le** [comment]
Yes, I use rqt_image_view to visualize the output topic <output_image_topic> (default:=/yolov5/image_out) in the launch file. Also make sure the arg <publish_image> is set to true. Let me know if it works.
