### ISSUE TITLE
Unable to echo /yolov5/detections

### ISSUE THREAD

**Issue by Matthijs20** [mats-robotics/yolov5_ros#4]
I am trying to publish the bounding boxes using the command: "rostopic echo /yolov5/detections" but i get the following error: Cannot load message class for [detection_msgs/boudingboxes]. are your messages built?
How can i fix this error?

**Comment by nhat-m-le** [comment]
Have you tried to follow the instruction which includes cloning and building the detection_msgs package?

**Comment by Matthijs20** [comment]
Yes i have followed all the instructions from the readme file. I can see the output image in rviz but there seems to be something wrong in my boudingboxes messages.

**Comment by astavitskiy** [comment]
May be you have to send source command with path to your setup.bash file?
If you in workspace directory, it will be
`source devel/setup.bash`

**Comment by nhat-m-le** [comment]
> Yes i have followed all the instructions from the readme file. I can see the output image in rviz but there seems to be something wrong in my boudingboxes messages.

Please give more details of the error.

**Comment by nhat-m-le** [comment]
Issue not reproducible.
