### ISSUE TITLE
Is it possible to test this yolov5 ROS Noetic repo with image files with my own weights?

### ISSUE THREAD

**Issue by TDVL** [mats-robotics/yolov5_ros#8]
Is it possible to test this yolov5 ROS Noetic repo with image files with my own weights?
I have a trained yolov5 network in Python, I have trained it in Colab using ultralytics repo.
Also, I have the saved best.pt weights.
Is it possible to use my weights? Also I have the *.yaml file of my dataset, however I don't know is it necessary here since I have the saved weights, I will not do the training ins ROS.
I would like to test my weights in this ROS Noetic repo on images.
Is it possible? If it is, how can I do that?

Thank you in advance,
Best regards,

**Comment by CaioRovetta15** [comment]
It's possible, you just have to change the weights and input topic in the launch file. If you get some errors just tell me, I just spent the day trying to solve them in my simulation using ros.

**Comment by TDVL** [comment]
Hi Caio,
I have changed the weights and the topic in the launch file, but I have got an error.
I have used my best.pt weights.
Can you provide exactly the changes that you have made?
Have you tested it on *.jpg image or on camera stream?
Did you use a virtual machine Ubuntu 20.04 and Noetic? Is it possible to use this with ROS Melodic?
Thank you.

**Comment by CaioRovetta15** [comment]
Hi @TDVL , what error did you get ?
In my launch file I just made these changes to the weights and the input topic.
![image](https://user-images.githubusercontent.com/70728881/190132393-22358932-08f0-4678-8060-3fd500342fd6.png)
I'm using it currently on my real machine that's running Ubuntu 20.04 and ros noetic. I don't know if you can run this package on ros melodic.
I had some errors with this package in the beginning too, so I've made some changes on the repository I forked and made a pull request.

**Comment by TDVL** [comment]
Hi,
Thank you very much. I will check it again, and I will report you.
I cannot find the screenshots of my errors at this moment, but I will try everything soon.
Hence, I should follow the guide from the this link, and later do the changes as you suggested me? https://github.com/mats-robotics/yolov5_ros
You have used a webcam, or something specific?
Is it possible to test this with *.jpg images and saved video files?

**Comment by CaioRovetta15** [comment]
I've used a video published in a ROS topic, if you want to use .jpg or saved video files you can publish it in a topic, or just use the detect.py in the yolov5 original repository.

**Comment by TDVL** [comment]
Hi,
I have built the repo on my VM.
Everything went OK, but after I have launched the yolov5, there is a CUDA AssertionError. Here is the screenshot
![Screenshot from 2022-09-14 14-47-10](https://user-images.githubusercontent.com/47524135/190159616-f7a2fc07-247a-4d74-a0a4-4299887806f5.png)
This yolov5 works simply in Python without CUDA on VM. 
What could be the problem?

**Comment by TDVL** [comment]
Hi,
Here is my launch file, I have published the image as the ROS topic, but I have still the AssertionError
![Screenshot from 2022-09-14 15-07-56](https://user-images.githubusercontent.com/47524135/190162562-1ebc03c8-1494-4b9c-b02c-f30af068ee02.png)

**Comment by TDVL** [comment]
Hi again,
I have installed CUDA with sudo command, but the error is still present.
![Screenshot from 2022-09-14 16-32-50](https://user-images.githubusercontent.com/47524135/190184029-1bba50d1-f9f0-43fe-93fe-7afa9008780b.png)
Also, I have tried to reinstall the torch, but it didn't help.
I think it could be a minor problem with the setup, but I cannot find what. The Yolov5 is fine, I think, I have checked and installed the requirements again from the *.txt file.
Did you see something like this before?
Thank you in advance.

**Comment by TDVL** [comment]
Hi Caio,
I have checked all the requirements, also CUDA is installed, but the error is still on.Here you are the screenshots.
The image is published well, I did like you have suggested. The launch file is changed according to your instructions.
I think CUDA is not needed here. I am using yolov5 in Python for inference with VBox VM without errors, I have only changed the weights.
What could be the problem? Thank you.
![Screenshot from 2022-09-19 12-32-40](https://user-images.githubusercontent.com/47524135/191001400-a016039a-e499-44f1-ab1c-6187338699e9.png)
![Screenshot from 2022-09-19 12-42-40](https://user-images.githubusercontent.com/47524135/191001415-d75a7347-748b-4641-a41d-47ad516020e9.png)

**Comment by TDVL** [comment]
Hello Caio,
I have solved the cpu error, but I have a new error now: AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from '/home/osboxes/catkin_ws/src/yolov5_ros/src/yolov5/models/yolo.py'>
![Screenshot from 2022-09-19 16-06-13](https://user-images.githubusercontent.com/47524135/191037406-30bdaa9b-111c-4998-a140-d44144f201ab.png)
I have followed the instructions. I have changed the launch file as you suggested, I have my good weights, but now I am stucke again.
Will you check this?

**Comment by CaioRovetta15** [comment]
Hi @TDVL, try to replace the yolov5 folder inside the src with the current version of their git, that worked for me. I think some modules have changed names, so you maybe need to check this.

**Comment by TDVL** [comment]
Hi,
I have replaced the yolov5 folder. I have a new error now.
![Screenshot from 2022-09-19 16-58-50](https://user-images.githubusercontent.com/47524135/191048599-7287bc3d-fead-473e-931d-8c10b690e414.png)
You have replaced the complete content of the yolov5 folder, or some files?
The *.pt files should not be related to the version, I think.

**Comment by flydragon2018** [comment]
same problem.  Any  solution?

**Comment by nhat-m-le** [comment]
all the errors are fixed with @CaioRovetta15 last PR
